import { Serie } from './serie.js';

export var dataSeries = [
    new Serie(1, "Breaking Bad", "AMC", 5),
    new Serie(2, "Planet Earth II", "BBC", 1),
    new Serie(3, "Planet Earth", "BBC", 1),
    new Serie(4, "Band of Brothers", "HBO", 1),
    new Serie(5, "Chernobyl", "HBO", 1),
    new Serie(6, "The Wire", "HBO", 5),
    new Serie(7, "Avatar: The Last Airbender", "Nickelodeon", 3),
    new Serie(8, "Blue Planet II", "BBC", 1),
    new Serie(9, "The Sopranos", "HBO", 6),
    new Serie(10, "Cosmos: A Spacetime Odyssey", "Fox", 1),
    new Serie(11, "Cosmos", "PBS", 1),
    new Serie(12, "Our Planet", "Netflix", 1),
    new Serie(13, "Game of Thrones", "HBO", 8),
    new Serie(14, "The World at War", "ITV", 1),
    new Serie(15, "Bluey", "ABC", 3),
    new Serie(16, "Rick and Morty", "Adult Swim", 7),
    new Serie(17, "Hagane no renkinjutsushi", "MBS", 2),
    new Serie(18, "Life", "BBC", 2),
    new Serie(19, "The Last Dance", "ESPN", 1),
    new Serie(20, "The Twilight Zone", "CBS", 10),
    new Serie(21, "Sherlock", "BBC", 8),
    new Serie(22, "The Vietnam War", "PBS", 1),
    new Serie(23, "Batman: The Animated Series", "Fox", 3),
    new Serie(24, "Shingeki no Kyojin", "MBS", 6),
    new Serie(25, "The Office", "NBC", 12),
    new Serie(26, "Scam 1992: The Harshad Mehta Story", "SonyLIV", 3),
    new Serie(27, "The Blue Planet", "BBC", 1),
    new Serie(28, "Arcane: League of Legends", "Netflix", 5),
    new Serie(29, "Shôgun", "FX", 8),
    new Serie(30, "Better Call Saul", "AMC", 6),
    new Serie(31, "Human Planet", "BBC", 1),
    new Serie(32, "Firefly", "Fox", 4),
    new Serie(33, "Frozen Planet", "BBC", 1),
    new Serie(34, "Clarkson's Farm", "Amazon Prime Video", 1),
    new Serie(35, "Hunter x Hunter", "NTV", 11),
    new Serie(36, "Only Fools and Horses", "BBC", 8),
    new Serie(37, "Death Note", "NTV", 5),
    new Serie(38, "The Civil War", "PBS", 3),
    new Serie(39, "Seinfeld", "NBC", 9),
    new Serie(40, "The Beatles: Get Back", "Disney+", 1),
    new Serie(41, "Dekalog", "TVP", 5),
    new Serie(42, "True Detective", "HBO", 4),
    new Serie(43, "Gravity Falls", "Disney Channel", 7),
    new Serie(44, "Sahsiyet", "Puhu TV", 3),
    new Serie(45, "Cowboy Bebop", "WOWOW", 5),
    new Serie(46, "Fargo", "FX", 5),
    new Serie(47, "Nathan for You", "Comedy Central", 3),
    new Serie(48, "Apocalypse: La 2ème guerre mondiale", "France 2", 11),
    new Serie(49, "Taskmaster", "Dave", 13),
    new Serie(50, "When They See Us", "Netflix", 14),
];
